version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: top5-tiao-carreiro_v2_backend
    container_name: top5-tiao-carreiro_v2_backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: top5-tiao-carreiro_v2_frontend
    container_name: top5-tiao-carreiro_v2_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: top5-tiao-carreiro_v2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: top5_tiao_carreiro_v2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: